# Generated by Django 3.0.2 on 2020-03-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mapsarcgismodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapsarcgismodel',
            options={'verbose_name': 'Arcgis maps'},
        ),
    ]
