# Generated by Django 3.0.2 on 2020-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200319_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsarcgismodel',
            name='slug',
            field=models.SlugField(default='', max_length=72),
            preserve_default=False,
        ),
    ]
