# Generated by Django 3.0.2 on 2020-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mapsarcgismodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=254)),
                ('recipient', models.CharField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Not sent'), (3, 'Requeued')], default=0)),
            ],
            options={
                'verbose_name': 'Email log',
                'db_table': 'email_log',
            },
        ),
    ]
