# Generated by Django 3.0.2 on 2020-03-20 16:57

from django.db import migrations, models
import source.apps.core.media


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsarcgismodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=source.apps.core.media.scramble_uploaded_filename),
        ),
    ]
