# Generated by Django 3.0.2 on 2020-03-22 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mapsarcgismodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCsseGisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True, verbose_name='Province/State')),
                ('country', models.CharField(blank=True, max_length=32, null=True, verbose_name='Country/Region')),
                ('last_update', models.DateTimeField(verbose_name='Last Update')),
                ('confirmed', models.PositiveIntegerField(verbose_name='Confirmed')),
                ('deaths', models.PositiveIntegerField(verbose_name='Deaths')),
                ('recovered', models.PositiveIntegerField(verbose_name='Recovered')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'report_cssegis',
            },
        ),
    ]
