# Generated by Django 3.0.2 on 2020-03-22 18:46

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200322_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcssegismodel',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country/Region'),
        ),
        migrations.AlterField(
            model_name='reportcssegismodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=112.2707, y=30.9756), srid=4326, unique=True),
        ),
    ]
