# Generated by Django 3.0.2 on 2020-03-22 20:29

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200322_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcssegismodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=112.2707, y=30.9756), srid=4326),
        ),
        migrations.AlterUniqueTogether(
            name='reportcssegismodel',
            unique_together={('country', 'location')},
        ),
    ]
