# Generated by Django 3.0.2 on 2020-03-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200322_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcssegismodel',
            options={'ordering': ('country', 'state'), 'verbose_name': 'CSSEGIS Report'},
        ),
    ]
