# Generated by Django 3.0.2 on 2020-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200322_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcssegismodel',
            options={'ordering': ('country', 'state', 'city'), 'verbose_name': 'CSSEGIS Report'},
        ),
        migrations.AddField(
            model_name='reportcssegismodel',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='City'),
        ),
    ]
